### ISSUE TITLE
FarseerPhysics物理引擎代码纠错和重构

### ISSUE THREAD

**Issue by experdot** [Nukepayload2/Nukepayload2.N2Engine#26]
该项工作旨在提高物理引擎的易用性，并使得引擎程序员能够完全了解[~~Box2D~~]FarseerPhysics的工作方式，这对以后的游戏开发有着重要作用。它包含以下列出但不是全部的子项：
- 文件组织：按照功能分类组织代码文件到不同的文件目录
- 文档注释：为公共的类、方法及属性提供Xml文档注释
- 代码重构：改善代码的内部结构以提升代码的质量与性能
- 错误修复：修复存在的BUG
- 快速开始：为第三方开发者提供"Quick Start"文档

**Comment by experdot** [comment]
Box2D被弃用，现改为FarseerPhysics引擎：
GitHub：https://github.com/craftworkgames/FarseerPhysics.Portable
Documentation：http://farseerphysics.codeplex.com/documentation

**Comment by experdot** [comment]
重新启用，物理引擎的维护Commit可以关联至这个Issue。

**Comment by Nukepayload2** [comment]
这个物理引擎用于编写测试代码的部分已经修改正常了。后续有问题再重开。
