### ISSUE TITLE
游戏可见对象树

### ISSUE THREAD

**Issue by Nukepayload2** [Nukepayload2/Nukepayload2.N2Engine#27]
**这是一个导致之前Demo失效的变更**
根据 @experdot 在 #10 提供的建议，我设计了使用场景的可见对象树。
根元素为 GameCanvas 
## GameCanvas

负责导航到不同的Scene，或者是直接显示Content中的GameVisual。
## Scene

Template属性是个VisualizingScrollViewer，就是 #10 讨论的那个。
Children属性包含多个Layer
定义了导航时的切换动画 #16 
包含通过摄像机名找摄像机的定义。摄像机定义了能控制画面卷动和缩放的矩阵。
## Layer

Children属性包含一组GameVisual
TiledLayer 包含一个矩阵，里面是某个图块的内容
PanelLayer 可按照绝对布局放置任何GameVisual
ControlLayer 包含UI元素，如：摇杆，按钮
ElementLayer 包含使用Box2D物理引擎的GameElement和相应的World对象
每一个Layer在Scene中链式存储，位于头部的在最底部绘制。
## GameVisual

SpiteVisual 必须先加载某些资源才可以绘制
DrawingVisual 不必加载资源，动态绘制 #18 

**每一个 GameVisual 都可设置：**
- CompositeTransform 控制 平移，3D旋转，缩放，扭曲 #17 
- Clip 使用可旋转的矩形或其它形状裁剪
- CompositeMode 定义如何叠加
- Opacity 定义透明度
- Effect 位图效果。包括光照等 #19  
- VisualStateManager 定义当前元素的状态。详见 #15 如何组织动画
- Triggers 触发器 #3 
- Behaviors 行为 #21 
## 继承设定

Scene, VisualizingScrollViewer 和 Layer 都继承 GameVisualContainer
GameVisualContainer继承GameVisual
这样以来，使用Scene和Layer, 或者是打算使用 VisualizingScrollViewer，甚至直接使用GameVisual都是可以的了。

**Comment by experdot** [comment]
现在的图层设计可实现场景的分层绘制，但开发人员无法为单个图层定制具体的渲染行为。通常，对图层做整体变换的性能要优于对图层内GameVisual逐一变换的做法，前者在代码逻辑上也比后者好实现（比如我想平移整个图层），你可以考虑为图层实现与GameVisual类似的属性与设置：

> CompositeTransform 控制 平移，3D旋转，缩放，扭曲 #17
Clip 使用可旋转的矩形或其它形状裁剪
CompositeMode 定义如何叠加
Opacity 定义透明度
Effect 位图效果。包括光照等 #19
VisualStateManager 定义当前元素的状态。详见 #15 如何组织动画
Triggers 触发器 #3
Behaviors 行为 #21

事实上，图层可以具有上述所有的设置。有的图形API里的做法是GameVisual继承自Layer,但不建议这样做。

**Comment by experdot** [comment]
我觉得图层在逻辑难以有明确的分类（现在的框架下），它既是Container又与GameVisual及其相似

**Comment by Nukepayload2** [comment]
@experdot
这就是为什么我让Layer和Scene继承GameVisualContainer，再让GameVisualContainer继承GameVisual

**Comment by experdot** [comment]
@Nukepayload2 
没注意到”继承设定”（一不小心把你上面评论弄坏了）

**Comment by Nukepayload2** [comment]
@experdot 你认为有什么遗漏的吗？如果没有，我就按这一套改了。

**Comment by Nukepayload2** [comment]
@experdot 
国庆之前必须完全确定 1.0 到底要实现什么。
根据这些功能顺序，我会把 1.0 划分为 1.0 Beta 1, 1.0 Beta 2, ... , 1.0 RC, 1.0 RTM。

**Comment by Nukepayload2** [comment]
GameLayer不再是GameVisualContainer，但是它还是有与之相同的功能。
这是因为 GameVisualContainer(Of T As GameVisual) 不能赋值到 GameVisualContainer(Of GameVisual) 。不允许在类使用协变。
这个变更要求向GameLayer添加成员之前必须判断它具体是什么类型的，并转换到那个类型。

**Comment by Nukepayload2** [comment]
现在对那些功能的引用已经创建了。元素也能按照树形渲染了。结帖。
