### ISSUE TITLE
事件触发器

### ISSUE THREAD

**Issue by Nukepayload2** [Nukepayload2/Nukepayload2.N2Engine#3]
## 作用对象
- [x] 游戏的画布
- [x] 画布里面的元素
## 模型
- [x] 在PCL层的可见元素添加触发器集合
- [x] 每一个触发器拥有 Attach 和 Detach 方法，用于添加事件处理器和移除事件处理器
- [x] 固定的事件触发器拥 不具备可修改的Action, 能转换为 GameObjectEventHandler(Of TSender, TEventArgs)
- [x] 事件-动作触发器拥有的Action 是 System.Delegate，不能获取事件数据。因此它是非泛型、轻量级的。
- [x] 事件-设定值触发器在事件发生时将一个 PropertyBinder 的值赋值给 另一个。
## 测试进度
- [x] 集成测试

**Comment by Nukepayload2** [comment]
事件-动作触发器的用例
```VB
       '复杂版本
        Dim trigger As New GameEventTrigger(Of GameVisual)(
            Sub(el) AddHandler ele.RemoveFromGameCanvasReuqested, removeRequested,
            Sub(el) RemoveHandler ele.RemoveFromGameCanvasReuqested, removeRequested)
        trigger.Attach(ele)
        '调试版本
        Dim triggerDebug As New GameEventTrigger(NameOf(ele.RemoveFromGameCanvasReuqested), removeRequested)
        triggerDebug.Attach(ele)
```

**Comment by nl8590687** [comment]
不错，支持一下
到时候添加上示例

**Comment by Nukepayload2** [comment]
事件-命令触发器
事件-设定值触发器
这两项功能不是必需的，并且可能导致性能问题。准备延后。

**Comment by Nukepayload2** [comment]
我意识到 Attach 和 Detach 应该在被添加和移除触发器集合的时候自动调用。这样可以方便编写和使用设计器。
