### ISSUE TITLE
主要基础类库的模块重新划分

### ISSUE THREAD

**Issue by Nukepayload2** [Nukepayload2/Nukepayload2.N2Engine#55]
## 概念
主要基础类库是指 Nukepayload2.N2Engine 和 Nukepayload2.N2Engine.Core 。
## 解决的问题
目前主要基础类库仅存在于两个模块中，依赖关系含糊不清。
这导致一个人想要更新一个功能时，另一个人需要等那个人把 Fork 后修改的部分 Merge 完成才能避免冲突。理论上这种状态下参与者越多，开发进展越迟缓。
## 方案
将 Nukepayload2.N2Engine 与 Nukepayload2.N2Engine.Core 合并，然后项目中按文件夹拆分。Utilities 文件夹除外，合并到其它项目中。
__规则__
* 每个小项目代码写在共享项目中，供被拆分的项目引用。
* 小项目之间可以引用其它小项目，不得引用主项目。
* 重构代码，去除不必要的小项目之间的依赖。

**Comment by Nukepayload2** [comment]
用 C# 写的那些 Android 和 iOS 类库可以被替换为 .NET Standard 2.0 类库。这样会去掉中间层，改进 Android 和 iOS 的存档和读档效率。

**Comment by Nukepayload2** [comment]
@experdot 基础类库 .NET Standard 用 1.3 你认为怎样？Mono 的类库可以兼容 .NET Framework 4.6，这正好对应 .NET Standard 1.3。

**Comment by Nukepayload2** [comment]
### 循环依赖关系的处置方式:
1. 如果循环依赖是工具类导致的，将它们拆分到各自的类库。
2. 如果是数据模型类导致的，基础数据模型放到核心类库，非基础放到各自的类库。
3. 如果一个功能明显是可选功能（例如：物理引擎，动画，行为），那么基础功能不要引用它。
4. 如果一个功能明显是基础功能，越基础在程序集依赖树越靠近根。
5. 如果存在互相引用，要么合并两个程序集，要么保留其中一个引用。如果难以区分功能是基础还是拓展，优先考虑合并。否则按照其它几条规则决定去掉哪个引用。

**Comment by experdot** [comment]
除了绘图API和可选功能外，相对独立的模块还包括音效、网络以及本地文件或设备I/O，这些在不同平台需要有不同的实现

**Comment by Nukepayload2** [comment]
@experdot 音效这个我写了好几套。安卓一套，iOS 一套，UWP 一套，WPF 一套。
IO 这个 .net standard 2.0 有完整的 API，我这几天正打算把之前用 c# 写的 xamarin 类库换掉。

**Comment by Nukepayload2** [comment]
准备升级 SDK。 #64

**Comment by Nukepayload2** [comment]
重新划分完毕。
