### ISSUE TITLE
针对不同区域的项目文件

### ISSUE THREAD

**Issue by Nukepayload2** [Nukepayload2/Nukepayload2.N2Engine#67]
一个大的sln项目文件在低端电脑存在性能问题。所以需要添加一些比较小的sln。

- [x] CoreParts.sln 包括组成核心类库 Nukepayload2.N2Engine 的全部项目和依赖的共享项目, 不包括核心类库本身
- [x] Core.sln 包括核心类库，依赖的共享项目，拓展核心逻辑类库，核心测试项目。

**Comment by experdot** [comment]
目录划分可能要考虑对将来核心类库发布Nuget包造成的影响。

**Comment by Nukepayload2** [comment]
@experdot 包含一切项目的解决方案文件还在。没有影响。

**Comment by Nukepayload2** [comment]
搞定~
没别的 sln 文件相关需求就先关闭了。
